# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

stages:
  - stage: 'Build'
    displayName: 'build the Spring application'
    jobs:
    - job: 'Build' 
      displayName: Build Maven Project
      pool: vs23822_AgentPool

      variables:
        buildConfiguration: 'Release'

      steps:
      - task: Maven@3
        displayName: 'Maven Package'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          mavenVersionOption: 'default'
          javaHomeOption: 'default'
          jdkUserInputPath: '/usr/lib/jvm/java-11-openjdk-amd64'
          jdkArchitectureOption: 'x64'
      - task: CopyFiles@2
        displayName: 'Copy Files to artifact staging directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - upload: $(Build.ArtifactStagingDirectory)
        artifact: drop
